# Generated by Django 5.2.17 on 2026-08-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(help_text='e.g. Tablet, Capsule, Syrup, Injection', max_length=100)),
                ('packaging', models.CharField(help_text='e.g. 10x10 Strips, 100ml Bottle', max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('indications', models.TextField(help_text='Primary medical uses / conditions treated')),
                ('storage_information', models.TextField(default='Store in a cool, dry place below 25°C. Protect from direct sunlight.')),
                ('manufacturer', models.CharField(default='Femiva Healthcare', max_length=255)),
                ('marketer', models.CharField(default='Femiva Healthcare', max_length=255)),
                ('prescription_required', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback web image URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Pill', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('doctor', 'Doctor'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('medical_store', 'Medical Store'), ('pharmacy', 'Pharmacy'), ('distributor', 'Distributor'), ('healthcare_business', 'Healthcare Business'), ('other', 'Other')], default='medical_store', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('doctor', 'Doctor'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('medical_store', 'Medical Store'), ('pharmacy', 'Pharmacy'), ('distributor', 'Distributor'), ('healthcare_business', 'Healthcare Business'), ('other', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('medicine_name_text', models.CharField(blank=True, help_text='Text format of medicine name if not linked directly', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_enquiries', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='api.medicine')),
            ],
            options={
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='api.medicinecategory'),
        ),
    ]
